apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmc-deployment
  labels:
    app: testmc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testmc
  template:
    metadata:
      labels:
        app: testmc
    spec:
      containers:
      - name: testmc
        image: testappcnr.azurecr.io/testmcimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: webapisvcsecret  
---
apiVersion: v1
kind: Service
metadata:
  name: testmcsvc
spec:
  type: LoadBalancer
  selector:
    app: testmc
  ports:
  - port: 80
